Repository acm-ucr/fencing-website, pull requests merged in 2025-03, with the labels that each got.

#105 81 combine divs
  src/components/Join/index.tsx
Labels: READY TO REVIEW

#107 Rishik pulipaka/mobile navbar
  package-lock.json
  package.json
  src/components/Navigation.tsx
  src/data/navigation.ts
Labels: READY TO REVIEW

#90 Moved div inside About Component + Changed About page.tsx
  src/app/about/page.tsx
  src/components/Home/About.tsx
Labels: READY TO REVIEW

#36 Add Join Component; run dev giving error
  src/app/join/page.tsx
  src/components/Join/index.tsx
Labels: READY TO REVIEW

#124 update favicon
  src/app/favicon.ico
Labels: READY TO REVIEW

#123 Fixed Mobile Responsiveness on Types.tsx
  src/components/Home/Types.tsx
Labels: READY TO REVIEW

#127 Added spacing to footer
  src/components/Landing.tsx
  src/components/events/gallery.tsx
Labels: READY TO REVIEW

#128 Join sizing
  src/components/Join/index.tsx
Labels: READY TO REVIEW

#126 Fixed responsiveness on Home below Types of Fencing Swords.
  src/components/Home/Scoring.tsx
  src/components/Home/Types.tsx
Labels: READY TO REVIEW

#110 Responsive Format & Scoring
  src/components/Home/Scoring.tsx
Labels: help wanted, READY TO REVIEW

#136 Footer icon animation
  src/components/Footer.tsx
Labels: READY TO REVIEW, Changes Requested

#137 fixed title component and added it across the site
  src/components/Board/Board.tsx
  src/components/Home/Landing.tsx
  src/components/Join/index.tsx
  src/components/Navigation.tsx
  src/components/Title.tsx
  src/components/events/gallery.tsx
  src/components/events/index.tsx
Labels: help wanted

#141 Make What We Do Responsive
  src/components/Home/What.tsx
Labels: READY TO REVIEW

#145 Events Page Motion
  src/components/events/index.tsx
Labels: READY TO REVIEW

#147 Added motion to 'What We Do!' + Changed Appearance of Content
  src/components/Home/About.tsx
  src/components/Home/Scoring.tsx
  src/components/Home/Types.tsx
  src/components/Home/What.tsx
Labels: READY TO REVIEW

#148 Join Page Image
  src/components/Join/index.tsx
Labels: READY TO REVIEW

#150 Event page motion
  src/components/events/index.tsx
Labels: READY TO REVIEW

#149 Animated title component
  src/components/Board/Board.tsx
  src/components/Join/index.tsx
  src/components/Title.tsx
  src/components/events/gallery.tsx
Labels: READY TO REVIEW
