Repository acm-ucr/fencing-website, pull requests merged in 2025-01, with the labels that each got.

#26 Created Scoring Component
  src/app/page.tsx
  src/components/About.tsx
  src/components/Scoring.tsx
  src/data/ScoringComponent.ts
Labels: good first issue, ready to merge

#18 Created the Navigation Component
  src/components/Navigation.tsx
  src/data/navigation.ts
Labels: READY TO REVIEW

#25 Join Landing Component
  package-lock.json
  package.json
  src/components/JoinLanding.tsx
Labels: READY TO REVIEW, Changes Requested
