Repository acm-ucr/fencing-website, pull requests merged in 2025-02, with the labels that each got.

#28 Benito/title component1
  src/app/page.tsx
  src/components/Title.tsx
Labels: help wanted, READY TO REVIEW, Changes Requested

#24 Created title component
  .gitignore
  .prettierignore
  public/Instagram.svg
  public/Link.svg
  public/background.svg
  public/epee.svg
  public/foil.svg
  public/mail.svg
  public/player.svg
  public/sabre.svg
  public/score.svg
  src/app/page.tsx
  src/components/Title.tsx
  tailwind.config.js
  tailwind.config.ts
Labels: Changes Requested

#23 What Component
  src/components/What.tsx
Labels: READY TO REVIEW, Changes Requested

#22 Button Component
  src/app/join/page.tsx
  src/components/About.tsx
  src/components/Button.tsx
  src/components/Landing.tsx
Labels: Changes Requested

#20 Added the footer image
  package-lock.json
  package.json
  public/Instagram.svg
  public/Link.svg
  public/background.svg
  public/footer.webp
  public/mail.svg
  src/components/Footer.tsx
  src/components/Navigation.tsx
  src/components/What.tsx
Labels: Changes Requested

#64 404-Page
  src/app/not-found.tsx
Labels: help wanted, READY TO REVIEW

#66 Fix
  package-lock.json
  public/background.webp
  public/board/sample.jpeg
  public/board/sample.webp
  src/app/board/page.tsx
  src/app/join/page.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/components/Board/Board.tsx
  src/components/Board/BoardCard.tsx
  src/components/Button.tsx
  src/components/Footer.tsx
  src/components/Home/About.tsx
  src/components/Home/Landing.tsx
  src/components/Home/Scoring.tsx
  src/components/Home/Types.tsx
  src/components/Home/What.tsx
  src/components/Join/Join.tsx
  src/components/Navigation.tsx
  src/components/Title.tsx
  src/data/board.ts
  src/data/navigation.ts
Labels: READY TO REVIEW

#61 Duvalincus/calendar
  src/app/globals.css
  src/components/events/index.tsx
  src/components/ui/calendar.tsx
Labels: ready to merge

#86 nav relative
  src/components/Navigation.tsx
Labels: ready to merge

#59 Gallery Implimented
  package-lock.json
  package.json
  public/gallery/gallery_1.webp
  public/gallery/gallery_10.webp
  public/gallery/gallery_11.webp
  public/gallery/gallery_12.webp
  public/gallery/gallery_13.webp
  public/gallery/gallery_14.webp
  public/gallery/gallery_15.webp
  public/gallery/gallery_16.webp
  public/gallery/gallery_17.webp
  public/gallery/gallery_18.webp
  public/gallery/gallery_19.webp
  public/gallery/gallery_2.webp
  public/gallery/gallery_20.webp
  public/gallery/gallery_21.webp
  public/gallery/gallery_22.webp
  public/gallery/gallery_23.webp
  public/gallery/gallery_24.webp
  public/gallery/gallery_25.webp
  public/gallery/gallery_26.webp
  public/gallery/gallery_27.webp
  public/gallery/gallery_28.webp
  public/gallery/gallery_29.webp
  public/gallery/gallery_3.webp
  public/gallery/gallery_30.webp
  public/gallery/gallery_31.webp
  public/gallery/gallery_32.webp
  public/gallery/gallery_33.webp
  public/gallery/gallery_34.webp
  public/gallery/gallery_35.webp
  public/gallery/gallery_4.webp
  public/gallery/gallery_5.webp
  public/gallery/gallery_6.webp
  public/gallery/gallery_7.webp
  public/gallery/gallery_8.webp
  public/gallery/gallery_9.webp
  src/components/Button.tsx
  src/components/events/gallery.tsx
  src/components/events/index.tsx
  src/data/gallery.ts
Labels: READY TO REVIEW

#55 Make Sabre Types Section Responsive
  src/components/Home/Types.tsx
Labels: READY TO REVIEW
